spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/testbootdb
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com.example.school: TRACE
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 1
  file:
    name: registryLog.log



# custom properties

# TODO: change key before using
application:
  security:
    jwt:
      secret: n+tZ+PZFpcPfwnpbbICPfSPaM/E/F/1gNpaLGL6Gazo=
      expiration: 3600000 # 1 hour
      refresh:
        expiration: 2419200000 # 28 days








# 1. Form for creating Student/parent/staff must create user account, and then redirecting for creating entity
#
#
#
#
#
